# Generated by Django 5.0.1 on 2024-04-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=55)),
                ('Email', models.EmailField(max_length=55)),
                ('Number', models.IntegerField(max_length=55)),
                ('Date', models.DateField()),
                ('Person', models.IntegerField(max_length=2)),
            ],
        ),
    ]
