# Generated by Django 5.0.1 on 2024-04-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_App', '0002_remove_order_diet_person_order_diet_kcal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_diet',
            name='Number',
            field=models.IntegerField(max_length=55),
        ),
    ]
